server.port: 8080

server.address: 0.0.0.0
spring.application.name: flight-system-gateway

services:
  urls:
    FLIGHT_SERVICE_URL: http://flight:8060/api/v1/flights
    PRIVILEGE_SERVICE_URL: http://bonus:8050/api/v1/privilege
    TICKETS_SERVICE_URL: http://ticket:8070/api/v1/tickets
