server.port: 8080

server.address: 0.0.0.0
spring.application.name: flight-system-gateway

services:
  urls:
    FLIGHT_SERVICE_URL: ${FLIGHT_SERVICE_URL}
    PRIVILEGE_SERVICE_URL: ${PRIVILEGE_SERVICE_URL}
    TICKETS_SERVICE_URL: ${TICKETS_SERVICE_URL}