server.port: 8080

server.address: 0.0.0.0
spring.application.name: flight-system-gateway

services:
  urls:
    flight-service-url: http://flight:8060/api/v1/flights
    privilege-service-url: http://bonus:8050/api/v1/privilege
    tickets-service-url: http://ticket:8070/api/v1/tickets
