{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
spec:
  tls:
  - hosts:
    {{- if .Values.ingress.hostname }}
      - {{ .Values.ingress.hostname }}
    {{- else}}
      - {{ .Release.Name }}-{{ .Chart.Name }}.{{ .Values.ingress.devopsDomain }}
    {{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
  {{- else}}
  - host: {{ .Release.Name }}-{{ .Chart.Name }}.{{ .Values.ingress.devopsDomain }}
  {{- end }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-gateway
            port:
              number: {{ .Values.service.port }}
{{- end }}
